### ISSUE TITLE
Develop a new module around Jaeger & OpenTracing

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud-incubator/spring-cloud-kubernetes#100]
In order to support Open Tracing initiative and to propose an alternative to Zipkin, I suggest to develop a new module around OpenTracing in order to report traces to Jaeger/OpenTracer dashboard, retrieve the tracer registered as a service and defined within the application.properties file.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/pull/101#issuecomment-308202338
