### ISSUE TITLE
Update io.fabric8 kubernetes-client version

### ISSUE THREAD

**Issue by trisberg** [spring-cloud-incubator/spring-cloud-kubernetes#108]
Any plans on updating the io.fabric8 kubernetes-client version which is currently at 2.4.1?

Also, what are you release plans for 0.2.0? I didn't see a milestone or date defined here.

**Comment by trisberg** [comment]
Currently the s-c-dataflow-server-kubernetes uses the io.fabric8 spring-cloud-kubernetes lib and it also has a dependency on the s-c-deployer-kubernetes project which uses the io.fabric8 kubernetes-client version 2.4.1, would be nice to have same version of the client lib

**Comment by iocanel** [comment]
It's a good idea to update to 2.4.1 and also get a release out.
