### ISSUE TITLE
Remove com.google.guava if possible

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud-incubator/spring-cloud-kubernetes#12]

**Comment by iocanel** [comment]
AFAIR, the code itself is not directly using guava, but was added because it was transitively required on run-time.

We can try to remove it and see how it goes.

**Comment by spencergibb** [comment]
Let's find out where the transitive dep is. We have an aversion to guava :-)

**Comment by spencergibb** [comment]
Looks like it's part of archaius. We have dep mgmt in netflix.  To remove the usage in s-c-kubernetes-ribbon, need to fix:
```
    protected KubernetesConfigKey(String configKey) {
        this.configKey = configKey;
        Type superclass = getClass().getGenericSuperclass();
        Assert.isTrue(superclass instanceof ParameterizedType,
                superclass + " isn't parameterized");
        Type runtimeType = ((ParameterizedType) superclass).getActualTypeArguments()[0];
        type = (Class<T>) TypeToken.of(runtimeType).getRawType();
    }
```

It's specifically `TypeToken.of()`. I'm worried to change it because there isn't a test to verify we don't regress.
