### ISSUE TITLE
Shouldn't reload configuration be disabled if config is disabled?

### ISSUE THREAD

**Issue by metacosm** [spring-cloud-incubator/spring-cloud-kubernetes#120]
Configuring automatic reload of configuration fails if configuration is disabled. Shouldn't this be handled more gracefully?

Description:
--
  |  
  | Field configMapPropertySourceLocator in org.springframework.cloud.kubernetes.config.reload.ConfigReloadAutoConfiguration$ConfigReloadAutoConfigurationBeans required a bean of type 'org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator' that could not be found.
  |  
  |  
  | Action:
  |  
  | Consider defining a bean of type 'org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator' in your configuration.

**Comment by spencergibb** [comment]
That's from the autoconfig report? I think it's fine to not run auto-configuration if a bean isn't present. I don't see this as a problem.
