### ISSUE TITLE
How to import multiple config maps

### ISSUE THREAD

**Issue by tomhughesnice** [spring-cloud-incubator/spring-cloud-kubernetes#129]
I am about to use the feature of this project to import Kubernetes configmap into my deployment.

https://github.com/spring-cloud-incubator/spring-cloud-kubernetes#configmap-propertysource

This allows me to specify a single a single configmap to import. I would like to specify a configmap for multiple things for example Postgres Settings, RabbitMq Setting, Logging settings that can be combined into a single yml file that my Spring boot app can import. 

Is this possible?

**Comment by spencergibb** [comment]
Is this your question https://stackoverflow.com/questions/46179113/kubernetes-spring-cloud-multiple-config-maps-being-used?

**Comment by tomhughesnice** [comment]
That question was one of my colleagues yes. It seems that you can import multiple secrets using this tool, but not configmaps. Is there a reason for this, or just not implemented?

**Comment by computerlyrik** [comment]
+1 - it would be nice to have something like `spring.config.location` in place for spring-cloud.

I went to the code a little - this class defines the Interface which `load`s only a `PropertySource`. If this could be extended somehow to return a `List` it would be possible to implement.

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceLocator.java

Has to be somewhat backwards-compatible.

**Comment by spencergibb** [comment]
I list is not needed since you can create a `CompositePropertySource` and add as many property sources as needed.
