### ISSUE TITLE
KubernetesApplicationContextInitializer always tries to parse certificates

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud-incubator/spring-cloud-kubernetes#131]
when you have `spring-cloud-kubernetes` on the classpath and you're running integration tests that start up Boot context, then regardless of the fact whether you use Kubernetes or not, by default it tries to parse certificates from your local folders. That's because the `KubernetesApplicationContextInitializer` does this in the constructor. 

In my opinion either it should be evaulated lazilly or it should be possible to disable loading by a system property or sth (e.g. `spring.cloud.kubernetes.enabled=false`).

**Comment by snowe2010** [comment]
This is a pretty big deal for us, as we want to disable kubernetes for production and just use it for development, but this makes it impossible, due to autoconfiguration ignoring all `spring.cloud.kubernetes.*` properties.

**Comment by spencergibb** [comment]
PRs welcome

**Comment by snowe2010** [comment]
What steps need to be taken to get this working? I would be glad to submit a PR, but am likely to break something due to the number of modules in this project.

**Comment by snowe2010** [comment]
I'm not sure how the Initializer is called (because it implements `ApplicationContextInitializer`?).

**Comment by snowe2010** [comment]
I seem unable to use `@ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled", matchIfMissing = true)` because the properties have not been initialized by the point that the `spring.factories` are loaded (bootstrap). I'm not sure how to get around this.

**Comment by dsyer** [comment]
The `Environment` is available in the `initialize()` method. If this feature needs to be implemented as an `ApplicationContextInitializer` (or similar), you would have to move  the logic to there.

**Comment by geoand** [comment]
@marcingrzejszczak @snowe2010 Which certificates do you mean? I can submit a PR fixing the issue, but I'm not sure I completely understand the issue

**Comment by spencergibb** [comment]
@geoand I think the logic in this line https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesApplicationContextInitializer.java#L35 needs to move to the `initialize()`.

**Comment by geoand** [comment]
@spencergibb That's my thought as well :), but I wanted to be sure before making any changes. 
That's why I would like @marcingrzejszczak or @snowe2010 to confirm which certificates are causing there issues.

**Comment by snowe2010** [comment]
@geoand yes that was exactly it. My attempts to move that logic were unsuccessful. I can try and dig up the code I had changed, but will not be able to get to it today.

**Comment by geoand** [comment]
@snowe2010 No problem, I'll check the issue out tomorrow and see what can be done. Thanks for the confirmation
