### ISSUE TITLE
Distinguish same key with secret or configmap

### ISSUE THREAD

**Issue by wdxxs2z** [spring-cloud-incubator/spring-cloud-kubernetes#178]
There has a scene: if i config two or more secret(configmap), but the secret's key has same name , how to distinguish them?

**Comment by geoand** [comment]
Hello @wdxxs2z ,

can you please be a little more specific about your use case?

**Comment by wdxxs2z** [comment]
Example, i have two db sources, mysql and redis, in secret data, they have one or two same key, such as password, uri, and our team have not use prefix to distinguish them, so if we use the spring-cloud-kubernetes-config, will their values be overridden?

**Comment by geoand** [comment]
Looking at the code for [Configmap](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/867f2319270b60937d3a12f5204c1079ef8d1665/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java#L28) and for  [Secret](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/867f2319270b60937d3a12f5204c1079ef8d1665/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/SecretsPropertySourceLocator.java#L28) it looks like ConfigMap has higher precedence. 

However I would argue that it's probably not the best practice to have the same keys for different things, no matter what the precedence rules are

**Comment by wdxxs2z** [comment]
@geoand , yeah~, if it support multiple secrets or configmaps, maybe it's better. thank you geoand!
