### ISSUE TITLE
Not compatible with spring boot 2?

### ISSUE THREAD

**Issue by sta-szek** [spring-cloud-incubator/spring-cloud-kubernetes#194]
Hi, I have spring boot 2.0.1.RELEASE, spring cloud Finchley.RELEASE, kubernetes starter 0.2.0.RELEASE and the application fails to start due to:
`Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.client.discovery.AbstractDiscoveryLifecycle`

I tried using other Finchley versions ( :man_facepalming: ) but without success.
However there is only one version in mvn central: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies

Also spring cloud says:
```
Finchley builds and works with Spring Boot 2.0.x, and is not expected to work with Spring Boot 1.5.x.

The Dalston and Edgware release trains build on Spring Boot 1.5.x, and are not expected to work with Spring Boot 2.0.x.
```
Ref: http://projects.spring.io/spring-cloud/

Is there any way to make it working?

**Comment by prafsoni** [comment]
@sta-szek use 0.3.0.RC1 with spring boot 2.0.x & spring cloud Finchley.RELEASE

**Comment by sta-szek** [comment]
Thanks, I will do tomorrow and let you know!

**Comment by sta-szek** [comment]
@prafsoni 
I need to do that also in plain spring application, do you have any clue for me what should I copy?
It is spring 4.x.

Or maybe are you aware of any existing project for that purpose? I searched and couldn't find.

**Comment by sta-szek** [comment]
@prafsoni I used 0.3.0.RC1 and locally: application builds and runs.
However I cannot build it on bamboo, because I got exception which I described in: https://github.com/fabric8io/kubernetes-client/issues/809

**Comment by sta-szek** [comment]
I tried to disable it during test phase but without luck:
```
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false
      enabled: false
