### ISSUE TITLE
Check if we want to keep sundrio for generating the bom

### ISSUE THREAD

**Issue by iocanel** [spring-cloud-incubator/spring-cloud-kubernetes#36]

**Comment by spencergibb** [comment]
It's currently disabled. We maintain each project's bom manually at the moment. It might be an interesting experiment to see if having it generated is a viable solution for us. Following the naming convention, the bom would be `spring-cloud-kubernetes-dependencies`.

**Comment by dsyer** [comment]
I can see some benefit in autogenerating a BOM (people seem to find it rather hard on average to do it properly when it's manual). Can we see a diff between the two?

**Comment by spencergibb** [comment]
@dsyer that will be part of the experiment. I disabled the auto-bom generation because it broke the build. It will need to be fixed to see the output.

**Comment by iocanel** [comment]
ok, I'll pick this up and see why it breaks!

**Comment by iocanel** [comment]
So, from what I see the `spring-cloud-kubernetes-dependencies` is used both internally and externally, so we can't really generate it on the fly.

What we can do is move the internal dependency management in the main pom and generate the pom that that we ship.

Why would we want to do that? 

1. The bom we ship just defines that stuff the user really needs. For example the current bom doesn't need to specify lombok, mock and spock related stuff. 

2. The generated bom doesn't contain `${project.version}` or ${xxx.version} _(which sometimes can cause issues)_ but the actual version number. 

3. Have the ability to automatically include all or some transitives into the bom.

4. Have the ability to generate multiple boms _(e.g bom and bom-with-tooling etc)_.

I don't know if the above make sense for this project. In other projects I've worked that had a huge amount of modules / dependencies (1) and (4) made a lot of sense. Also, in many cases we've seen issues that we resolved with (2) _(can't really recall specifics)_.

**Comment by iocanel** [comment]
So, the question is if (1) worths the trouble. 

FWIW, I created a pull request, so that I can show how it looks like.
With this configuration it automatically includes all own project modules and nothing else.

If we want to include things like the kubernetes client and model we can add to the configuration something like:

    <dependencies>
        <includes>
            <include>io.fabric8:kubernetes-*</include>
        </includes>
    </dependencies>

**Comment by dsyer** [comment]
Does `io.fabric8:kubernetes` not have a BOM?

**Comment by iocanel** [comment]
It does

**Comment by dsyer** [comment]
Then shouldn't we include that (instead of `io.fabric8:kubernetes-*`)?

**Comment by iocanel** [comment]
I need to check if this is supported by the plugin.

**Comment by iocanel** [comment]
It is supported, but it unwraps the boms to check for version conflicts etc.

**Comment by spencergibb** [comment]
So what does a generated bom look like?

**Comment by iocanel** [comment]
It looks like this: https://gist.github.com/iocanel/ff1e96127be772852f63aef3424e30f9

**Comment by spencergibb** [comment]
Thanks for doing the experiment. To me it doesn't seem like it gaining us much and it doesn't fit the current spring cloud pattern.

**Comment by iocanel** [comment]
Ok, let's remove it completely then.

**Comment by spencergibb** [comment]
Yup, I agree

**Comment by dsyer** [comment]
Definitely we don't want those jackson dependencies in there (they will flag as warnings with Maven 3.4 in any project that uses this BOM). So probably there are issues with the kubernetes BOM that we'll have to watch out for even if we do a manual BOM for this project.

(FWIW we have a similar unresolved issue with the AWS BOM.)

**Comment by iocanel** [comment]
The kubernets-client provides multiple boms, one with just the artifacts it ships and one with a minimal set of dependencies. So let's switch to the thin bom.

**Comment by iocanel** [comment]
Hmmm, I guess that `unwarpping` boms with the ability to filter out stuff is an additional value point for generating a bom :-)

**Comment by iocanel** [comment]
Switching to the thin bom, is not trivial, because it seems that someone adds dependencyManagement for okhttp which breaks the tests.

**Comment by dsyer** [comment]
If something in kubernetes needs a different version of okhttp (or any other dependency) than the rest of spring cloud or spring boot that is an issue we. We'd to look into. What is the origin of the conflict? Can we reconcile it here? Do we need to change the other BOM?

**Comment by iocanel** [comment]
The kubernetes-client is using but not requiring okhttp version 3.4.1 (it should work with any most 3+ version). 
The kubernetes-mockwebserver (an other project which we use for testing) is also using okhttp 3.4.1 and depends on okhttp's mockwebserver 3.4.1 which has a hard requirement on okhttp 3.4.1.

spring-cloud-netflix-dependencies adds dependency management for okhttp version 3.3.1 

So we end up using okhttp 3.3.1 and okhttp-mockwebserver 3.4.1 which doesn't work.

Possible solutions:
- align
- explicitly add dm for okhttp-mockwebserver (a bit prone to break again).
- import the kubernetes-client-bom-with-deps before the netflix one.

**Comment by iocanel** [comment]
I think that we can close this now
