### ISSUE TITLE
Perform a 0.2.0.RELEASE

### ISSUE THREAD

**Issue by davinkevin** [spring-cloud-incubator/spring-cloud-kubernetes#42]
Hi, 

Sorry if I miss it, but I want to use Spring cloud Kubernetes and I didn't find any information on how to integrate it. 

The doc said to add it as dependency to my pom.xml, but the code example use a variable as version `${latest.version` (with a missing bracket).
I don't find it in maven central or mvn repository. I only have the old one under the `groupId` `io.fabric8`

I will use the `io.fabric8` version `0.1.4` as a fallback but I would like to switch to this version 😄 

Thanks

**Comment by spencergibb** [comment]
Are you asking if there has been a release? There has not been one under the new project. @iocanel what do you think?

**Comment by iocanel** [comment]
I think that its a good time to go for a release. It will help people who want to migrate.

**Comment by davinkevin** [comment]
Glad to hear it ! Do you plan it soon ? I can postponed the implementation and directly use the new version 😄

**Comment by spencergibb** [comment]
I think we still have a few things to fix up, but I don't see an issue of doing one in the next few weeks.

**Comment by cmoulliard** [comment]
What are the issues that you want to fix in order to release ?

**Comment by spencergibb** [comment]
There are some issues about the k8s client that should be fixed.

**Comment by davinkevin** [comment]
Any news about this release ? Not even an SNAPSHOT release to let people try it 😄  in our project

**Comment by iocanel** [comment]
@spencergibb: at the moment I am not aware of any pending k8s client issues? Is there something that needs to be done?

**Comment by spencergibb** [comment]
@davinkevin there have been snapshots for a long while in https://repo.spring.io/libs-snapshot-local  See https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-kubernetes/

@iocanel as far as doing a release, I don't think so.

**Comment by iocanel** [comment]
So, that means we can release?

**Comment by spencergibb** [comment]
I think so. I will likely need to do it since you won't have access to publish under the `org.springframework.cloud` group id in maven central.

**Comment by cmoulliard** [comment]
Can we release 0.20.2 after pushing and reviewing my 2 last PR @spencergibb, @iocanel ?

**Comment by spencergibb** [comment]
I think that's fine. I'm prepping for OSCON, moving house the weekend and OSCON next week so I wouldn't be able to get to it until after then.

**Comment by jniebuhr** [comment]
Any news on this? It's been a while.

**Comment by cmoulliard** [comment]
I think that it is time now to release as we have reviewed the README (see last PR), added new examples, fix some issues, ....

**Comment by spencergibb** [comment]
The build has a failing test, and I'd like #108 to be fixed.

**Comment by mehdikhelif** [comment]
Hello, any news on this ?  Is there any remaining issues to be fixed ?

**Comment by spencergibb** [comment]
Likely this week

**Comment by mehdikhelif** [comment]
Great. Thanks Spencer

**Comment by davinkevin** [comment]
I'm in the starting block for that 🚗
