### ISSUE TITLE
Document relationship between s-c-kubernetes, kubernetes client, kubenetes model & API

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud-incubator/spring-cloud-kubernetes#47]
As `spring-cloud-kubernetes`uses librairies released by the `Fabric8` project, that should be great to include within the documentation a table describing How this project is aligned with the Kubernetes API (1.3, 1.4, 1.5, ...) through the Fabric8 Kubernetes Client (= 1.x or 2.x) and Fabric8 Kubernetes Model (= 1.0.x)

```
[INFO] +- org.springframework.cloud:spring-cloud-kubernetes-core:jar:0.2.0.BUILD-SNAPSHOT:compile
[INFO] |  +- io.fabric8:kubernetes-client:jar:2.2.0:compile
[INFO] |  |  +- io.fabric8:kubernetes-model:jar:1.0.67:compile
```

**Comment by iocanel** [comment]
@cmoulliard: can we close this one now?
