### ISSUE TITLE
Ribbon and/or circuit breaker doesn't detect that pods are backs

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud-incubator/spring-cloud-kubernetes#80]
When we follow this [scenario](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example) to demonstrate circuit breaker/ribbon, the first part of the demo works very well but not when we scale up to `1`, the pod of the `name service` after it was scale to `0`.
It is required to restart the pod `greeting service` which contains the circuit breaker + ribbon

Maybe the problem could be related to a too long health check readiness probe or that circuit breaker/ribbon doesn't check the list of the pod available after a fallback

To be investigated

**Comment by cmoulliard** [comment]
In order to understand the problem I have created a test case where no circuit breaker is defined in order to check first Ribbon.

Surprisingly, when the restTemplate.getObject is called [here](https://github.com/cmoulliard/spring-cloud-kubernetes/blob/27f4b4a3570ac5fb60ecc4d0b49342028909b14f/spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonFallbackTest.java#L119-L119), then 2 endpoints are still present & discovered by Ribbon while they have should been deleted previously using the Kubernetes client. 

Do I miss something @iocanel ?

![screenshot 2017-05-16 09 23 03](https://cloud.githubusercontent.com/assets/463790/26094421/3ef357f2-3a1a-11e7-8668-20f9908fbec5.png)

**Comment by iocanel** [comment]
@cmoulliard: not sure how this is supposed to work. 
But it doesn't sound that weird, given that endpoints are resources not managed by the user.

**Comment by cmoulliard** [comment]
> not sure how this is supposed to work.

So, you think that we can't simulate this scenario ?

- Start 2 MockServer replying to request issued for this path `/greeting`
- Register the 2 MockServers as endpoints for the kubeMockerServer (`testapp-a` and `testapp-b`)
- Add test case (1) to check if we get a response using as Ribbon Client name `testapp` to call the endpoint --> `http://testapp/greeting`
- Delete the endpoints from kubeMockServer
- Test (2) that we can't get a response as endpoints have been removed (ribbon should sync here with kube ?)
- Add test case (3) to check if we get a response when calling the endpoint --> `http://testapp/greeting`. Endpoints should be registered agai

**Comment by cmoulliard** [comment]
Scenario described initially as issue retested successfully. It is required to wait more time as the endpoints are not registered as quickly as we can suppose when the pods are recreated

```
oc get endpoints/name-service
NAME           ENDPOINTS   AGE
name-service               17m
....
oc get endpoints/name-service
NAME           ENDPOINTS          AGE
name-service   172.17.0.10:8080   17m
....
oc get endpoints/name-service
NAME           ENDPOINTS                           AGE
name-service   172.17.0.10:8080,172.17.0.11:8080   17m
```
